name: test workFlow
on: workflow_dispatch
jobs: 
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: start flow
        run: java --version
      - run: mvn --version
      - name: run test and generate allure report
        continue-on-error: true
        run: mvn clean test
  
