name: run regression

on: [push, workflow_dispatch]


permissions:
  id-token: write
  contents: write
  pages: write


jobs: 
  run-test:
    name: Run regression test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: start flow
        run: java --version
      - run: mvn --version
      - name: run test and generate allure report
        continue-on-error: true
        run: mvn clean test

      - run: ls -la
      - run: cd target && ls -la

      - name: Upload allure report
        uses: actions/upload-artifact@v4
        with: 
          name: allure-results
          path: target/allure-results
          retention-days: 1

  generate-report:
    needs: run-test
    name: Generate report
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - run: mvn --version

      - run: ls -la

      - run: mvn allure::report

      - run: ls -la

      - name: Upload generated report
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path: _site
          retention-days: 1

  publish-report:
    needs: generate-report
    name: Publish report
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - run: ls -la
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./target/allure-report
      - name: Deploy to gitHub pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9

